version: '3'

services:
  postgres:
    image: openmaptiles/postgis
    volumes:
      - "pgdata:/var/lib/postgresql/data"
        #      - ./custom_configs/postgresql.conf:/etc/postgresql.conf
        #    command: postgres -c 'config_file=/etc/postgresql.conf'
    environment:
     - POSTGRES_DB=gis
     - POSTGRES_USER=gis
    restart: unless-stopped

  cassandra:
    image: cassandra:latest
    volumes:
     - "cassandra_data:/var/lib/cassandra"
    restart: unless-stopped

  tilerator:
    build: ./tilerator
    depends_on:
      - cassandra
      - postgres
      - redis
    environment:
      - TILERATOR_MODE=api # This service will not process tiles
    volumes:
      - update_tiles_data:/data/update_tiles_data

  tilerator-worker:
    build: ./tilerator
    environment:
      - TILERATOR_NUM_WORKERS=ncpu # Number of workers (or ncpu by default)
    depends_on:
      - cassandra
      - postgres
      - redis
    restart: unless-stopped

  redis:
    image: redis:latest
    command: redis-server --appendonly yes # to enable persistence
    volumes:
      - "redisdata:/data"
    restart: unless-stopped

  load_db:
    build: ./load_db
    environment:
      - INVOKE_CONFIG_FILE=config.yml
    volumes:
      - input_data:/data/input
      - imposm_generated_data:/data/generated
      - update_tiles_data:/data/update_tiles_data
    depends_on:
      - postgres

  kartotherian:
    build: ./kartotherian

  telegraf:
    build: ./telegraf

volumes:
  pgdata:
  cassandra_data:
  redisdata:
  input_data:
  imposm_generated_data:
  update_tiles_data:
