version: '3'
services:
  postgres:
    build: ./postgis
    volumes:
      - "pgdata:/var/lib/postgresql/data"
    environment:
     - POSTGRES_DB=gis
     - POSTGRES_USER=gis
  cassandra:
    image: cassandra:latest
  tileserv:
    build: ./tileserv
    environment:
      - NODE_PATH='/opt/tilerator/node_modules'
      - TILERATOR_PORT=16354
    depends_on:
      - cassandra
      - tilegen
      - redis
    ports:
      - "16534:16534"
  redis:
    image: redis:latest
  tilegen:
    build: ./tilegen
    volumes:
    - ./data:/data
    depends_on:
      - postgres

volumes:
  pgdata:
