version: '3'

services:
  postgres:
    image: openmaptiles/postgis
    volumes:
      - "pgdata:/var/lib/postgresql/data"
    environment:
     - POSTGRES_DB=gis
     - POSTGRES_USER=gis

  cassandra:
    image: cassandra:latest
    volumes:
     - "cassandra_data:/var/lib/cassandra"

  tilerator:
    build: ./tilerator
    depends_on:
      - cassandra
      - load_db
      - redis

  redis:
    image: redis:latest
    command: redis-server --appendonly yes # to enable persistence
    volumes:
      - "redisdata:/data"

  load_db:
    build:
      context: ./load_db
      dockerfile: Dockerfile-initial
    volumes:
      - input_data:/data/input
      - imposm_generated_data:/data/generated
      - update_tiles_data:/data/update_tiles_data
    depends_on:
      - postgres
      - redis  # used to tell tilerator the db is loaded

  update:
    build:
      context: ./load_db
      dockerfile: Dockerfile-update
    environment:
      - OSMOSIS_WORKING_DIR=/data/update_tiles_data
    volumes:
      - imposm_generated_data:/data/imposm
      - update_tiles_data:/data/update_tiles_data

  kartotherian:
    build: ./kartotherian
    depends_on:
      - tilerator

volumes:
  pgdata:
  cassandra_data:
  redisdata:
  input_data:
  imposm_generated_data:
  update_tiles_data:

