version: '3'

services:
  update:
    build:
      context: ./load_db
      dockerfile: Dockerfile-update
    environment:
      - OSMOSIS_WORKING_DIR=/data/update_tiles_data
    volumes:
      - imposm_generated_data:/data/imposm
      - update_tiles_data:/data/update_tiles_data
