apiVersion: v1
kind: ReplicationController
metadata:
  name: postgres-rc
spec:
  replicas: 1
  selector:
    app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        env:
        - name: POSTGRES_DB
          value: gis
        - name: POSTGRES_USER
          value: gis
        image: openmaptiles/postgis
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres
